version: "3"

services:
  django:
    container_name: "django_tree_menu"
    build: .
    command: bash -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
